import json
import logging

logger = logging.getLogger(__name__)

def parse_file_plan(raw_text: str) -> dict:
    """
    Parse the file plan generated by the LLM.
    Expects raw_text to be a JSON string mapping file paths to their contents.
    """
    try:
        # Sometimes LLMs wrap JSON in markdown blocks even when told not to.
        # Let's do some basic cleanup.
        text = raw_text.strip()
        if text.startswith("```json"):
            text = text[7:]
        if text.startswith("```"):
            text = text[3:]
        if text.endswith("```"):
            text = text[:-3]
        
        text = text.strip()
        return json.loads(text)
    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse LLM response as JSON: {e}\\nRaw text: {raw_text[:200]}...")
        return {}
    except Exception as e:
        logger.error(f"Unexpected error parsing file plan: {e}")
        return {}

