import { autoForgeApi } from "../api/autoForgeApi";

function isImage(path = "") {
  return /\.(png|jpg|jpeg|svg|webp)$/i.test(path);
}

function isHtml(path = "") {
  return /\.html$/i.test(path);
}

function isDiagramSource(path = "") {
  return /\.(mmd|puml)$/i.test(path);
}

function getFileName(path = "") {
  return path.split(/[\\/]/).pop() || path;
}

function getTitle(path = "") {
  return getFileName(path)
    .replace(/\.(png|jpg|jpeg|svg|webp|html|mmd|puml)$/i, "")
    .replaceAll("_", " ")
    .replaceAll("-", " ");
}

/**
 * Shows Architect Agent visual outputs.
 *
 * Supports:
 * - PNG/JPG/SVG UML diagrams
 * - HTML diagram/report previews inside iframe
 * - Mermaid/PlantUML source files
 */
export default function DiagramPreview({ paths = [], onReadArtifact }) {
  const imagePaths = paths.filter(isImage);
  const htmlPaths = paths.filter(isHtml);
  const sourcePaths = paths.filter(isDiagramSource);

  const hasVisuals = imagePaths.length > 0 || htmlPaths.length > 0;

  return (
    <section className="diagram-preview-section">
      <div className="section-title-row">
        <div>
          <h3>UML Diagrams and HTML Views</h3>
          <p>Visual architecture outputs generated by the Architect Agent.</p>
        </div>
      </div>

      {!hasVisuals && (
        <div className="diagram-empty">
          <p>No visual UML diagram or HTML output found yet.</p>
          <small>
            Check whether export_visuals is enabled and whether Mermaid,
            PlantUML, or Graphviz generated .png, .svg, or .html files.
          </small>
        </div>
      )}

      {imagePaths.length > 0 && (
        <>
          <h4 className="sub-output-heading">Image Diagrams</h4>

          <div className="diagram-grid">
            {imagePaths.map((path) => (
              <div className="diagram-card" key={path}>
                <div className="diagram-card-header">
                  <strong>{getTitle(path)}</strong>

                  <a
                    href={autoForgeApi.getArtifactFileUrl(path)}
                    target="_blank"
                    rel="noreferrer"
                  >
                    Open
                  </a>
                </div>

                <img
                  src={autoForgeApi.getArtifactFileUrl(path)}
                  alt={getTitle(path)}
                />

                <span>{path}</span>
              </div>
            ))}
          </div>
        </>
      )}

      {htmlPaths.length > 0 && (
        <>
          <h4 className="sub-output-heading">HTML Diagram / Report Views</h4>

          <div className="html-preview-grid">
            {htmlPaths.map((path) => (
              <div className="html-preview-card" key={path}>
                <div className="diagram-card-header">
                  <strong>{getTitle(path)}</strong>

                  <div className="mini-actions">
                    <button type="button" onClick={() => onReadArtifact(path)}>
                      View Code
                    </button>

                    <a
                      href={autoForgeApi.getArtifactFileUrl(path)}
                      target="_blank"
                      rel="noreferrer"
                    >
                      Open
                    </a>
                  </div>
                </div>

                <iframe
                  title={getTitle(path)}
                  src={autoForgeApi.getArtifactFileUrl(path)}
                  className="html-preview-frame"
                  sandbox=""
                />

                <span>{path}</span>
              </div>
            ))}
          </div>
        </>
      )}

      {sourcePaths.length > 0 && (
        <>
          <h4 className="sub-output-heading">Diagram Source Files</h4>

          <div className="source-file-list">
            {sourcePaths.map((path) => (
              <button
                key={path}
                type="button"
                onClick={() => onReadArtifact(path)}
              >
                <strong>{getFileName(path)}</strong>
                <span>{path}</span>
              </button>
            ))}
          </div>
        </>
      )}
    </section>
  );
}