import asyncio
import inspect
import json
import os
from pathlib import Path

import yaml

from agents.uiux_agent.schemas import UIUXPack, WireframeSpec
from agents.uiux_agent.flow_builder import (
    build_default_screens,
    build_user_flow,
    build_mermaid_from_flow,
)
from agents.uiux_agent.prompt import build_wireframe_prompt
from agents.uiux_agent.parser import clean_html_output
from agents.uiux_agent.wireframe_builder import fallback_wireframe_html
from agents.uiux_agent.renderer import render_mermaid_to_png, render_html_to_png
from agents.uiux_agent.traceability_builder import build_ui_traceability


class UIUXAgent:
    """
    UI/UX Agent for AutoForge.

    Inputs:
    - Approved SRS JSON
    - Approved API contract YAML

    Outputs:
    - User flows JSON + Mermaid + PNG
    - AI-generated wireframe HTML + PNG screenshots
    - Traceability JSON
    - UIUXPack JSON + Markdown summary

    Important:
    - Screens are discovered automatically from SRS + OpenAPI.
    - User flows are generated automatically from discovered screens.
    - Wireframes are generated by Ollama first.
    - If Ollama fails, the agent uses dynamic fallback templates.
    """

    def __init__(self, llm_provider=None):
        self.llm_provider = llm_provider
        self.output_dir = Path(os.getenv("OUTPUT_DIR", "outputs"))

    def validate_inputs(self, srs: dict, api_contract: dict) -> dict:
        """
        Checks whether approved SRS and API contract contain enough data
        for UI/UX generation.
        """

        questions = []

        if not srs.get("functional_requirements"):
            questions.append("Approved SRS must contain functional_requirements.")

        if not api_contract.get("paths"):
            questions.append("Approved API contract must contain OpenAPI paths.")

        return {
            "valid": len(questions) == 0,
            "clarification_required": len(questions) > 0,
            "questions": questions,
        }

    def load_approved_inputs(
        self,
        run_id: str,
        srs_version: str,
        api_version: str,
    ) -> tuple[dict, dict]:
        """
        Loads approved SRS and approved API contract from outputs folder.
        """

        srs_path = (
            self.output_dir
            / "runs"
            / run_id
            / "srs"
            / srs_version
            / f"SRS_{srs_version}.json"
        )

        api_path = (
            self.output_dir
            / "runs"
            / run_id
            / "architecture"
            / api_version
            / f"OpenAPI_{api_version}.yaml"
        )

        if not srs_path.exists():
            raise FileNotFoundError(f"Approved SRS not found: {srs_path}")

        if not api_path.exists():
            raise FileNotFoundError(f"Approved API contract not found: {api_path}")

        srs = json.loads(srs_path.read_text(encoding="utf-8"))
        api_contract = yaml.safe_load(api_path.read_text(encoding="utf-8"))

        return srs, api_contract

    def _run_llm_generate(self, prompt: str) -> str:
        """
        Calls the configured LLM provider.

        This supports both:
        - synchronous provider.generate(prompt)
        - asynchronous provider.generate(prompt)

        This is important because different agents in your project may use
        slightly different provider implementations.
        """

        if not self.llm_provider:
            raise RuntimeError("No LLM provider configured for UI/UX Agent.")

        result = self.llm_provider.generate(prompt)

        if inspect.isawaitable(result):
            return asyncio.run(result)

        return result

    def _generate_wireframe_html_with_llm(
        self,
        project_name: str,
        screen,
        srs: dict,
        api_contract: dict,
        change_request: str | None,
    ) -> tuple[str, str]:
        """
        Generates one wireframe HTML using Ollama.

        Returns:
            (html, generation_source)

        generation_source:
            - "llm" if Ollama generated valid HTML
            - "fallback" if Ollama failed and fallback was used
        """

        prompt = build_wireframe_prompt(
            project_name=project_name,
            screen=screen,
            srs=srs,
            api_contract=api_contract,
            change_request=change_request,
        )

        try:
            raw_output = self._run_llm_generate(prompt)
            html = clean_html_output(raw_output)
            return html, "llm"

        except Exception as error:
            print(
                f"[WARN] LLM wireframe generation failed for "
                f"{screen.id} - {screen.name}: {error}"
            )

            html = fallback_wireframe_html(
                project_name=project_name,
                screen=screen,
                change_request=change_request,
            )

            return html, "fallback"

    def generate_design_pack(
        self,
        run_id: str,
        srs_version: str = "v1",
        api_version: str = "v1",
        uiux_version: str = "v1",
        include_admin: bool = True,
        render_images: bool = True,
        change_request: str | None = None,
        status: str = "generated",
        previous_version: str | None = None,
        use_llm_wireframes: bool = True,
    ) -> dict:
        """
        Generates full UI/UX design pack.

        Fully automated pipeline:
        1. Load approved SRS + approved API contract.
        2. Auto-discover screens from SRS/API.
        3. Auto-build user flow from discovered screens.
        4. Generate Mermaid and PNG flow.
        5. Generate each wireframe using Ollama.
        6. Validate HTML.
        7. Render HTML to PNG.
        8. Save versioned artifacts.
        """

        srs, api_contract = self.load_approved_inputs(
            run_id=run_id,
            srs_version=srs_version,
            api_version=api_version,
        )

        validation = self.validate_inputs(srs, api_contract)
        if not validation["valid"]:
            return validation

        project_name = srs.get("project_name", "AutoForge E-commerce Platform")

        base_dir = self.output_dir / "runs" / run_id / "uiux" / uiux_version
        flows_dir = base_dir / "flows"
        wireframes_dir = base_dir / "wireframes"

        flows_dir.mkdir(parents=True, exist_ok=True)
        wireframes_dir.mkdir(parents=True, exist_ok=True)

        # 1. Automatically discover screens.
        screens = build_default_screens(
            srs=srs,
            api_contract=api_contract,
            include_admin=include_admin,
            change_request=change_request,
        )

        # 2. Automatically build user flow.
        user_flow = build_user_flow(
            screens=screens,
            change_request=change_request,
        )

        mermaid = build_mermaid_from_flow(user_flow)

        flow_json_path = flows_dir / f"user_flows_{uiux_version}.json"
        flow_mmd_path = flows_dir / f"user_flows_{uiux_version}.mmd"

        flow_json_path.write_text(
            json.dumps(user_flow.model_dump(), indent=2),
            encoding="utf-8",
        )

        flow_mmd_path.write_text(mermaid, encoding="utf-8")

        flow_png_path = None
        if render_images:
            flow_png_path = render_mermaid_to_png(flow_mmd_path)

        # 3. Generate wireframes.
        wireframe_html_paths = []
        wireframe_png_paths = []
        wireframe_generation_sources = {}

        for screen in screens:
            html_path = wireframes_dir / screen.file_name

            if use_llm_wireframes:
                html, source = self._generate_wireframe_html_with_llm(
                    project_name=project_name,
                    screen=screen,
                    srs=srs,
                    api_contract=api_contract,
                    change_request=change_request,
                )
            else:
                html = fallback_wireframe_html(
                    project_name=project_name,
                    screen=screen,
                    change_request=change_request,
                )
                source = "fallback"

            html_path.write_text(html, encoding="utf-8")
            wireframe_html_paths.append(str(html_path))
            wireframe_generation_sources[screen.id] = source

            if render_images:
                png_path = html_path.with_suffix(".png")
                rendered = render_html_to_png(html_path, png_path)

                if rendered:
                    wireframe_png_paths.append(rendered)

        wireframe_spec = WireframeSpec(
            version=uiux_version,
            screens=screens,
        )

        wireframes_json_path = wireframes_dir / f"wireframes_{uiux_version}.json"
        wireframes_json_path.write_text(
            json.dumps(wireframe_spec.model_dump(), indent=2),
            encoding="utf-8",
        )

        # 4. Traceability.
        traceability = build_ui_traceability(screens)

        trace_path = base_dir / f"trace_uiux_{uiux_version}.json"
        trace_path.write_text(
            json.dumps([link.model_dump() for link in traceability], indent=2),
            encoding="utf-8",
        )

        # 5. UIUXPack.
        uiux_pack = UIUXPack(
            project_name=project_name,
            version=uiux_version,
            source_srs_version=srs_version,
            source_api_version=api_version,
            status=status,
            screens=screens,
            user_flows=[user_flow],
            traceability=traceability,
            flow_mmd_path=str(flow_mmd_path),
            flow_png_path=flow_png_path,
            wireframe_html_paths=wireframe_html_paths,
            wireframe_png_paths=wireframe_png_paths,
        )

        pack_json_path = base_dir / f"UIUXPack_{uiux_version}.json"
        pack_md_path = base_dir / f"UIUXPack_{uiux_version}.md"

        pack_json_path.write_text(
            json.dumps(uiux_pack.model_dump(), indent=2),
            encoding="utf-8",
        )

        pack_md_path.write_text(
            self._render_markdown_summary(
                pack=uiux_pack,
                change_request=change_request,
                previous_version=previous_version,
                wireframe_generation_sources=wireframe_generation_sources,
            ),
            encoding="utf-8",
        )

        if change_request:
            revision_log_path = base_dir / f"revision_note_{uiux_version}.txt"
            revision_log_path.write_text(
                f"Previous version: {previous_version or 'N/A'}\n"
                f"New version: {uiux_version}\n"
                f"Change request: {change_request}\n"
                f"Updated artifacts: user flows + wireframes + traceability\n",
                encoding="utf-8",
            )
        else:
            revision_log_path = None

        return {
            "run_id": run_id,
            "uiux_version": uiux_version,
            "previous_version": previous_version,
            "change_request": change_request,
            "use_llm_wireframes": use_llm_wireframes,
            "wireframe_generation_sources": wireframe_generation_sources,
            "updated_artifacts": [
                "auto_discovered_screens",
                "user_flows",
                "wireframes",
                "wireframe_pngs",
                "flow_png",
                "traceability",
                "uiux_pack",
            ],
            "uiux_pack_path": str(pack_json_path),
            "markdown_path": str(pack_md_path),
            "flow_json_path": str(flow_json_path),
            "flow_mmd_path": str(flow_mmd_path),
            "flow_png_path": flow_png_path,
            "wireframes_json_path": str(wireframes_json_path),
            "wireframe_html_paths": wireframe_html_paths,
            "wireframe_png_paths": wireframe_png_paths,
            "traceability_path": str(trace_path),
            "revision_note_path": str(revision_log_path) if revision_log_path else None,
        }

    def revise_design_pack(
        self,
        run_id: str,
        current_version: str,
        new_version: str,
        change_request: str,
        srs_version: str = "v1",
        api_version: str = "v1",
        include_admin: bool = True,
        render_images: bool = True,
        use_llm_wireframes: bool = True,
    ) -> dict:
        """
        Revises UI/UX output as a new version.

        It regenerates:
        - screen inventory
        - user flow
        - LLM-generated wireframes
        - screenshots
        - traceability
        """

        current_pack_path = (
            self.output_dir
            / "runs"
            / run_id
            / "uiux"
            / current_version
            / f"UIUXPack_{current_version}.json"
        )

        if not current_pack_path.exists():
            raise FileNotFoundError(f"Current UIUXPack not found: {current_pack_path}")

        return self.generate_design_pack(
            run_id=run_id,
            srs_version=srs_version,
            api_version=api_version,
            uiux_version=new_version,
            include_admin=include_admin,
            render_images=render_images,
            change_request=change_request,
            status="revised",
            previous_version=current_version,
            use_llm_wireframes=use_llm_wireframes,
        )

    def _render_markdown_summary(
        self,
        pack: UIUXPack,
        change_request: str | None = None,
        previous_version: str | None = None,
        wireframe_generation_sources: dict | None = None,
    ) -> str:
        """
        Human-readable Markdown summary.
        """

        lines = [
            f"# UI/UX Design Pack: {pack.project_name}",
            "",
            f"**Version:** {pack.version}",
            f"**Status:** {pack.status}",
            f"**Source SRS:** {pack.source_srs_version}",
            f"**Source API Contract:** {pack.source_api_version}",
        ]

        if previous_version:
            lines.append(f"**Previous Version:** {previous_version}")

        if change_request:
            lines.extend([
                "",
                "## Revision Request",
                change_request,
                "",
                "## Revision Impact",
                "- Screens re-discovered from approved SRS + API contract",
                "- User flows regenerated",
                "- Wireframes regenerated using LLM-first generation",
                "- Traceability regenerated",
            ])

        lines.extend([
            "",
            "## Screens",
        ])

        for screen in pack.screens:
            source = ""
            if wireframe_generation_sources:
                source = f" — generation: {wireframe_generation_sources.get(screen.id, 'unknown')}"

            lines.append(
                f"- **{screen.id} — {screen.name}**: {screen.description}{source}"
            )

        lines.append("")
        lines.append("## User Flows")

        for flow in pack.user_flows:
            lines.append(f"- **{flow.id} — {flow.name}** ({flow.actor})")

        lines.append("")
        lines.append("## Traceability")

        for link in pack.traceability:
            lines.append(f"- {link.requirement_id} → {link.screen_id} ({link.screen_name})")

        return "\n".join(lines)