from typing import List, Optional, Literal
from pydantic import BaseModel, Field


class UIScreen(BaseModel):
    """
    Represents one UI screen generated by the UI/UX Agent.

    Example:
    UI-SCR-02 = Catalog screen
    """

    id: str
    name: str
    file_name: str
    description: str
    route: str
    related_requirements: List[str]


class FlowNode(BaseModel):
    """
    Represents one node in the user flow.
    """

    id: str
    label: str
    screen_id: Optional[str] = None
    related_requirements: List[str] = Field(default_factory=list)


class FlowEdge(BaseModel):
    """
    Represents a connection between two flow nodes.
    """

    from_node: str
    to_node: str
    condition: Optional[str] = None


class UserFlow(BaseModel):
    """
    Machine-readable user flow.

    This will also be converted into Mermaid .mmd.
    """

    id: str
    name: str
    actor: str
    nodes: List[FlowNode]
    edges: List[FlowEdge]


class WireframeSpec(BaseModel):
    """
    Machine-readable summary of generated wireframes.
    """

    version: str
    screens: List[UIScreen]


class UITraceLink(BaseModel):
    """
    Traceability between a functional requirement and UI screen.
    """

    requirement_id: str
    screen_id: str
    screen_name: str
    reason: str


class UIUXPack(BaseModel):
    """
    Final UI/UX Design Pack.

    Saved as:
    UIUXPack_vX.json
    UIUXPack_vX.md
    """

    project_name: str
    version: str
    source_srs_version: str
    source_api_version: str
    status: Literal["generated", "revised"] = "generated"

    screens: List[UIScreen]
    user_flows: List[UserFlow]
    traceability: List[UITraceLink]

    flow_mmd_path: Optional[str] = None
    flow_png_path: Optional[str] = None
    wireframe_html_paths: List[str] = Field(default_factory=list)
    wireframe_png_paths: List[str] = Field(default_factory=list)